# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51303102e2e9abbc96c0e1da90dd9e8c65faff10dd45c9c3b71b37b803abadc9843c50975c6ad520b63eeddabfede1ea812fc1a42f7986265baaddfc5e3ad2f1

test:
  secret_key_base: bd4e488c9ad92d909aee4a4a45b8d97de3e2993ff13082acb805df9c02673938be443faf4d809738fb1b50800cac9ca0661cf41cac97365e5ec0608ffbbfc3fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
